### ISSUE TITLE
How to install Vacuum for Zed?

### ISSUE THREAD

**Issue by mliebelt** [kovapatrik/zed-vacuum#1]
I was glad to find that repository referenced, and I would like to give it a try. But I found no information how to install that extension to Zed. Any help available? Ok, I found out myself how to install it, but next step would be to use it. What is the kind of support I can expect from the extension? I have no idea, and looking for a command with `vacuum` in it did not help.

**Comment by kovapatrik** [comment]
As long as the vaccuum extension is installed, it should lint all yaml/json files which have the "openapi" tag.

**Comment by mliebelt** [comment]
That means, when I open an OpenAPI file (which is then recognized by the plugin), the file is then checked automatically? Thank you for answering my question.

**Comment by kovapatrik** [comment]
Yes, it should work like that.
